//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirlinesReservationSystem.Models
{
 

    [Table("Flight")]
    public class Flight
    {
        [Required]
        [Key]
        public int flightId { get; set; }
        public string flightName { get; set; }
        [Required]
        public int seatFirstclass { get; set; }
        [Required]
        public int seatBusinessclass { get; set; }
        [Required]
        public int seatEconomyclass { get; set; }



        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
