//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirlinesReservationSystem.Models
{
   

    [Table("Schedule")]
    public class Schedule
    {
        public int scheduleId { get; set; }
        [ForeignKey("Flight")]
        public int flightId { get; set; }
        [Required]
        public string source { get; set; }
        [Required]
        public int sourceId { get; set; }
        [Required]
        public string dest { get; set; }
        [Required]
        public int destId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime scheduleDate { get; set; }
        [Required]
        public TimeSpan depatureTime { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime arrivalDate { get; set; }
        [Required]
        public TimeSpan arrivalTime { get; set; }
        [Required]
        public string status { get; set; }
        [Required]
        public int FCseats { get; set; }
        [Required]
        public int BCseats { get; set; }
        [Required]
        public int ECseats { get; set; }
        [Required]
        public double costFirst { get; set; }
        [Required]
        public double costBusiness { get; set; }
        [Required]
        public double costEconomy { get; set; }
        [Required]
        public string traveltype { get; set; }


        public virtual Flight Flight { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
