//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Ticket")]
    public class Ticket
    {
        [Required]
        [Key]
        public int ticketId { get; set; }
        public string UserId { get; set; }
        [ForeignKey("Flight")]
        public int flightId { get; set; }
        [ForeignKey("Schedule")]
        public int scheduleId { get; set; }
        [ForeignKey("Payment")]
        public int paymentId { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime dateOfJourney { get; set; }
        public int seatNo { get; set; }
        public string passengerName { get; set; }
        public char gender { get; set; }
        [Phone]
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string travelclass { get; set; }
        public string emergencyContact { get; set; }

        public virtual Flight Flight { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
